##################################################################################
#         About
##################################################################################
# Reuseable workflow to be called from content repos. 
# Build and deploy app bundle for android
##################################################################################
name: Android Build
  
  # Only keep one active build per ref (e.g. pr branch, push branch, triggering workflow ref)
concurrency:
    group: android-build-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
  
on:
    workflow_call:
      inputs:
        CONTENT_BRANCH:
          type: string
          default: ""
        LFS_USED:
          required: true
          type: boolean     
        APP_CODE_BRANCH:
          required: true
          type: string
        DEPLOYMENT_NAME:
          required: true
          type: string
        PARENT_DEPLOYMENT_NAME:
          type: string
          default: ""
        PARENT_DEPLOYMENT_REPO:
          type: string
          default: ""
        PARENT_DEPLOYMENT_BRANCH:
          type: string
          default: ""
        ENCRYPTED:
          required: true
          type: boolean  
      secrets:
        DEPLOYMENT_PRIVATE_KEY:
          required: false
        GOOGLE_SERVICES_JSON: 
          required: true
        SIGNING_KEY: 
          required: true
        ALIAS: 
          required: true
        KEY_STORE_PASSWORD: 
          required: true
        KEY_PASSWORD: 
          required: true
                  
  
jobs:
  
    build_action:
        uses: ./.github/workflows/app-build.yml
        with: 
          CONTENT_BRANCH: ${{ inputs.CONTENT_BRANCH }}   
          LFS_USED: ${{ inputs.LFS_USED }}  
          APP_CODE_BRANCH: ${{ inputs.APP_CODE_BRANCH }}  
          DEPLOYMENT_NAME: ${{ inputs.DEPLOYMENT_NAME }}  
          PARENT_DEPLOYMENT_NAME: ${{ inputs.PARENT_DEPLOYMENT_NAME }}  
          PARENT_DEPLOYMENT_REPO: ${{ inputs.PARENT_DEPLOYMENT_REPO }}  
          PARENT_DEPLOYMENT_BRANCH: ${{ inputs.PARENT_DEPLOYMENT_BRANCH }}  
          ENCRYPTED: ${{ inputs.ENCRYPTED }}            
        secrets: 
          DEPLOYMENT_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}  
  
    build_android:
      runs-on: ubuntu-latest
      needs: build_action
      env:
        GIT_SHA: ${{ needs.web_build.outputs.GIT_SHA }}
      steps:
        
        - name: Check out app code
          uses: actions/checkout@v3
          with:
            repository: "IDEMSInternational/open-app-builder.git"
            ref: ${{inputs.APP_CODE_BRANCH}}
  
        - name: Checkout parent repo if needed
          if: inputs.PARENT_DEPLOYMENT_REPO != ''
          uses: actions/checkout@v3
          with:
            path: ".idems_app/deployments/${{inputs.PARENT_DEPLOYMENT_NAME}}"
            repository: ${{inputs.PARENT_DEPLOYMENT_REPO}}
            ref: ${{inputs.PARENT_DEPLOYMENT_BRANCH}}
  
        - name: Checkout deployment
          uses: actions/checkout@v3
          with:
            path: ".idems_app/deployments/${{inputs.DEPLOYMENT_NAME}}"

        - name: Populate Encryption key
          if: inputs.ENCRYPTED != ''
          run: echo "${{secrets.DEPLOYMENT_PRIVATE_KEY}}" > ./.idems_app/deployments/${{secrets.DEPLOYMENT_NAME}}/encrypted/private.key

        - name: Populate google-services.json
          env:
            GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          run: echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
        #############################################################################
        #         Sync web files
        # Setup node same way as web build to allow calling `npx cap sync` command
        #############################################################################
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 20.17.0          
        - uses: actions/cache/restore@v3
          id: cache
          with:
            path: ./.yarn/cache
            key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-node-modules-yarn-v1-
              
        - name: Install node modules
          run: yarn install --immutable
  
        - name: Set deployment
          run: yarn workflow deployment set $DEPLOYMENT_NAME --skip-refresh
  
        - name: Prepare android configuration
          run: yarn workflow android
             
        - name: Download Build Artifact
          uses: actions/download-artifact@v4
          with:
            name: www

        - name: Extract Build folder
          run: |
            mkdir www
            tar -xf artifact.tar --directory www
        - name: Sync Android Files
          run: npx cap sync
        #############################################################################
        #         Android Build
        #############################################################################
          # Java version mapping: https://stackoverflow.com/a/47457251/5693245
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: "zulu"
            java-version: "17"
            java-package: jdk
            cache: "gradle"
        - name: Setup Android SDK
          uses: android-actions/setup-android@v2
  
          # Debug APK
        - name: Build Android Debug APK
          working-directory: android
          run: ./gradlew :app:assembleDebug
  
        - name: Upload debug apk
          uses: actions/upload-artifact@v4
          with:
            name: debug_apk
            path: android/app/build/outputs/apk/debug/app-debug.apk
  
          # Signed Release Bundle
        - name: Build Android Release Bundle
          working-directory: android
          run: ./gradlew :app:bundleRelease
  
        - name: Sign Android Release
          id: sign_aab
          uses: r0adkll/sign-android-release@v1
          with:
            releaseDirectory: ./android/app/build/outputs/bundle/release
            signingKeyBase64: ${{ secrets.SIGNING_KEY }}
            alias: ${{ secrets.ALIAS }}
            keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
            keyPassword: ${{ secrets.KEY_PASSWORD }}
            
        - name: Upload release bundle
          uses: actions/upload-artifact@v4
          with:
            name: release_bundle
            path: ${{steps.sign_aab.outputs.signedReleaseFile}}
       
