##################################################################################
#         About
##################################################################################
# Reuseable workflow to be called from content repos. 
# Allows for parent repo. 
# Must specify all below secrets and variables - see documentation for details
##################################################################################

name: Build App
  
  # Only keep one active build per ref (e.g. pr branch, push branch, triggering workflow ref)
concurrency:
    group: app-build-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
  
on:
    workflow_call:
      inputs:
        BUILD_FLAGS:
          type: string
          default: ""
        CONTENT_BRANCH:
          type: string
          default: ""
        LFS_USED:
          required: true
          type: boolean  
        APP_CODE_BRANCH:
          required: true
          type: string
        DEPLOYMENT_NAME:
          required: true
          type: string
        PARENT_DEPLOYMENT_NAME:
          type: string
          default: ""
        PARENT_DEPLOYMENT_REPO:
          type: string
          default: ""
        PARENT_DEPLOYMENT_BRANCH:
          type: string
          default: ""
        ENCRYPTED:
          required: true
          type: boolean  
      secrets:
        DEPLOYMENT_PRIVATE_KEY:
          required: false

      outputs:
        GIT_SHA:
          description: "Git SHA of build head"
          value: ${{ jobs.build.outputs.GIT_SHA }}
  
jobs:
    build:
      outputs:
        GIT_SHA: ${{ steps.populate.outputs.GIT_SHA }}
      env:
        ARTIFACT: test
      runs-on: ubuntu-latest

      steps:
        - name: Check out app code
          uses: actions/checkout@v4
          with:
            repository: "IDEMSInternational/open-app-builder.git"
            ref: ${{inputs.APP_CODE_BRANCH}}
  
        - name: Checkout parent repo if needed
          if: inputs.PARENT_DEPLOYMENT_REPO != ''
          uses: actions/checkout@v4
          with:
            path: ".idems_app/deployments/${{inputs.PARENT_DEPLOYMENT_NAME}}"
            repository: ${{inputs.PARENT_DEPLOYMENT_REPO}}
            ref: ${{inputs.PARENT_DEPLOYMENT_BRANCH}}
            # main repo does not use lfs so explicitly omit
            lfs: false
  
        - name: Checkout deployment
          uses: actions/checkout@v4
          with:
            ref: ${{inputs.CONTENT_BRANCH}}
            path: ".idems_app/deployments/${{inputs.DEPLOYMENT_NAME}}"
            fetch-depth: 0
            # content repo optionally includes lfs
            lfs: ${{inputs.LFS_USED}}
            
        - name: Populate Encryption key
          if: inputs.ENCRYPTED
          run: echo "${{secrets.DEPLOYMENT_PRIVATE_KEY}}" > ./.idems_app/deployments/${{inputs.DEPLOYMENT_NAME}}/encrypted/private.key
  
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 20.17.0

  
      #############################################################################
      #         Node Modules
      # Manually restore any previous cache to speed install
      # As immutable install will not change cache only save new cache if not hit
      # Uses fine-grained methods from https://github.com/actions/cache
      #############################################################################
        - uses: actions/cache/restore@v4
          id: cache
          with:
            path: ./.yarn/cache
            key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-node-modules-yarn-v1-
        - name: Install node modules
          run: yarn install --immutable
        - uses: actions/cache/save@v4
          if: steps.cache.outputs.cache-hit != 'true'
          with:
            path: ./.yarn/cache
            key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('yarn.lock') }}
    
        - name: Set deployment
          run: yarn workflow deployment set $DEPLOYMENT_NAME --skip-refresh

        - name: Build
          run: yarn build ${{inputs.BUILD_FLAGS}}
  
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: "www/"
            name: www  
