##################################################################################
#         About
##################################################################################
# Reuseable workflow to be called from content repos. 
# Deploy preview url for labelled PRs
# Specifies deployment target based on pr target branch
# Must specify all below secrets and variables - see documentation for details
#
#
##################################################################################
name: Deploy PR Preview
concurrency:
  group: deploy-pr-preview-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
    inputs:
      FIREBASE_HOSTING_TARGET:
        required: true
        type: string
      FIREBASE_PROJECT_ID:
        required: true
        type: string
      FIREBASE_HOSTING_CHANNEL:
        required: true
        type: string   
      LFS_USED:
        required: true
        type: boolean  
      APP_CODE_BRANCH:
        required: true
        type: string
      DEPLOYMENT_NAME:
        required: true
        type: string
      PARENT_DEPLOYMENT_NAME:
        type: string
        default: ""
      PARENT_DEPLOYMENT_REPO:
        type: string
        default: ""
      PARENT_DEPLOYMENT_BRANCH:
        type: string
        default: ""
      ENCRYPTED:
        required: true
        type: boolean  
    secrets:
      DEPLOYMENT_PRIVATE_KEY:
        required: false      
      FIREBASE_SERVICE_ACCOUNT:
        required: true

jobs:
  build:    
    if: contains(github.event.pull_request.labels.*.name, 'test - preview')
    uses: ./.github/workflows/app-build.yml
    with:
      BUILD_FLAGS: --configuration "production,preview"
      CONTENT_BRANCH: ${{ github.ref }}  
      LFS_USED: ${{ inputs.LFS_USED }}  
      APP_CODE_BRANCH: ${{ inputs.APP_CODE_BRANCH }}  
      DEPLOYMENT_NAME: ${{ inputs.DEPLOYMENT_NAME }}  
      PARENT_DEPLOYMENT_NAME: ${{ inputs.PARENT_DEPLOYMENT_NAME }}  
      PARENT_DEPLOYMENT_REPO: ${{ inputs.PARENT_DEPLOYMENT_REPO }}  
      PARENT_DEPLOYMENT_BRANCH: ${{ inputs.PARENT_DEPLOYMENT_BRANCH }}  
      ENCRYPTED: ${{ inputs.ENCRYPTED }}            
    secrets: 
      DEPLOYMENT_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}  

  deploy_preview:  
    needs: build
    runs-on: ubuntu-latest
    outputs:
      urls: ${{ steps.deploy.outputs.urls }}
    steps:
      - uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: www
          
      - name: Extract Build folder
        run: |
          mkdir www
          tar -xf artifact.tar --directory www

      - name: Populate Firebase Targets
        run: |
          FIREBASE_RC_TARGETS=$(jq -n \
            --argjson "${{inputs.FIREBASE_PROJECT_ID}}" \
            '{"hosting":{"${{inputs.FIREBASE_HOSTING_TARGET}}":["${{inputs.FIREBASE_HOSTING_TARGET}}"]}}' \
            '$ARGS.named'
            )
          FIREBASE_RC=$(jq -n \
          --argjson projects '{"default":"${{inputs.FIREBASE_PROJECT_ID}}"}' \
          --argjson targets "$FIREBASE_RC_TARGETS" \
          '$ARGS.named'
          )
          echo $FIREBASE_RC | jq '.'
          echo $FIREBASE_RC > .firebaserc

      - name: Populate Firebase JSON
        run: |
          FIREBASE_JSON_HOSTING=$(jq -n \
          --arg target "${{ inputs.FIREBASE_HOSTING_TARGET }}" \
          --arg public "www" \
          --argjson ignore '["firebase.json"]' \
          --argjson rewrites '[{"source": "**","destination": "/index.html"}]' \
          '$ARGS.named'
          )
          FIREBASE_JSON=$(jq -n \
          --argjson hosting "[$FIREBASE_JSON_HOSTING]" \
          '$ARGS.named'
          )
          echo $FIREBASE_JSON | jq '.'
          echo $FIREBASE_JSON > firebase.json
          
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "${{ inputs.FIREBASE_PROJECT_ID }}"
          target: "${{ inputs.FIREBASE_HOSTING_TARGET }}"
          expires: 14d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
